return {
  -- {
  --   "nvim-neotest/neotest",
  --   dependencies = {
  --     "nvim-neotest/neotest-python",
  --     "nvim-treesitter/nvim-treesitter",
  --     "nvim-neotest/nvim-nio",
  --     "nvim-lua/plenary.nvim",
  --     "antoinemadec/FixCursorHold.nvim",
  --   },
  --   opts = {
  --     adapters = {
  --       ["neotest-python"] = {
  --         dap = {
  --           justMyCode = true, -- Set to true to only debug your code, not dependencies
  --           type = "Active File",
  --         },
  --         runner = "pytest",
  --         pytest_discover_instances = true,
  --       },
  --     },
  --   },
  -- },
  -- {
  --   "neovim/nvim-lspconfig",
  --   opts = {
  --     servers = {
  --       pyright = {
  --         capabilities = (function()
  --           local capabilities = vim.lsp.protocol.make_client_capabilities()
  --           capabilities.textDocument.publishDiagnostics.tagSupport.valueSet = { 2 }
  --           return capabilities
  --         end)(),
  --         settings = {
  --           python = {
  --             analysis = {
  --               disableOrganizeImports = true,
  --               diagnosticSeverityOverrides = {
  --                 -- reportUnusedVariable = "warning", -- or anything
  --               },
  --               typeCheckingMode = "basic",
  --             },
  --           },
  --         },
  --       },
  --       ruff = {
  --         cmd_env = { RUFF_TRACE = "messages" },
  --         init_options = {
  --           settings = {
  --             logLevel = "error",
  --           },
  --         },
  --         keys = {
  --           {
  --             "<leader>co",
  --             LazyVim.lsp.action["source.organizeImports"],
  --             desc = "Organize Imports",
  --           },
  --         },
  --       },
  --       ruff_lsp = {},
  --     },
  --     -- setup = {
  --     --   ["ruff"] = function()
  --     --     LazyVim.lsp.on_attach(function(client, _)
  --     --       --use ruff as a formatter and pyright as linter, type checker and hover provider
  --     --       client.server_capabilities.hoverProvider = false
  --     --       client.server_capabilities.diagnosticProvider = nil
  --     --     end, "ruff")
  --     --   end,
  --     -- },
  --   },
  -- },
}
