[general]
import = [
    "~/.config/alacritty/base16-dark.toml",
    "~/.config/alacritty/keybindings.toml",
    "alacritty-theme/themes/gruvbox_dark.toml",
]
[font]
normal = { family = "menlo", style = "Regular" }
