[general]
import = [
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/catppuccin-frappe.toml",
]
[mouse]
hide_when_typing = true
[cursor]
style.shape = "Underline"
[font]
normal = { family = "UbuntuMono Nerd Font Mono", style = "Regular" }
size = 16.0

[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 25

decorations = "transparent"

option_as_alt = "Both"

[scrolling]
history = 5000
[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
]
