[general]
import = [
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/catppuccin-frappe.toml",
]
[mouse]
hide_when_typing = true
[cursor]
style.shape = "Underline"
[font]
normal = { family = "UbuntuMono Nerd Font Mono", style = "Regular" }
size = 15.0

[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

# option_as_alt = "Both"
