[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]
[mouse]
hide_when_typing = false
[cursor]
style.shape = "Underline"
vi_mode_style = "Block"
[font]
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
normal = { family = "UbuntuSansMono Nerd Font Mono", style = "Regular" }

size = 14.0

[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 25

decorations = "transparent"

option_as_alt = "OnlyLeft"

[scrolling]
history = 5000
[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
